### ISSUE TITLE
Accessibility Testing Matrix

### ISSUE THREAD

**Issue by distantorigin** [fizzstudio/svg-aria-test#14]
Below is my current testing matrix, for reference. This issue will be updated with further comments detailing any changes to this matrix in the future. (Hopefully in a table instead of markdown headings.)

#### Windows

```Version 20H2 (OS Build 19042.867)```

##### Browsers

- Chromium (Microsoft Edge, Google Chrome, Brave, etc, v 89.X)
- Mozilla Firefox (v. 87.0)

##### Screen Readers

- JAWS (v. 2021.2102.34)
- Narrator
- NVDA (v. 2020.4)

#### macOS

```Version 10.15.7```

*Note*- Currently I don't have access to a macOS machine. This will be changing soon. For completeness, lateest versions are listed.

##### Browsers

- Safari (v. 14.1)

##### Screen Readers

- VoiceOver

#### iOS

```Version 14.4.2```

##### Browsers

- Mobile Safari (v. 14.4.2)

##### Screen Readers

- VoiceOver

**Comment by shelbyelavsky** [comment]
**Updated testing matrix**
Computers: 
Windows 11 Build 22000.438
MacBook Pro/ macOS Monterey 12.0.1

Screen readers:
JAWS 2022.2112.24 ILM
NVDA 2021.3.1
VoiceOver

Browsers: 
Chrome Version 97.0.4692.99
Firefox 96.0.3
Safari 15.1 (17612.2.9.1.20)
